[package]
name = "three_em"
version = "0.1.0"
authors = ["andreespirela <andreespirela@outlook.com>", "Divy Srivastava <dj.srivastava23@gmail.com>"]
edition = "2021"
resolver = "2"
build = "build.rs"

[[bench]]
name = "wasm"
harness = false

[features]
wasm = ["js-sys", "wasm-bindgen"]
default = []

[dependencies]
v8 = "0.34.0"
deno_core = "0.107.0"
deno_crypto = "0.39.0"
deno_url = "0.25.0"
deno_web = "0.56.0"
deno_webidl = "0.25.0"
tokio = { version = "1.10.1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
async-trait = "0.1.51"
pico-args = "0.4.2"
colored = "2"
reqwest = { version = "0.11", features = ["blocking", "json"] }
local_ipaddress = "0.1.3"
rsa = "0.5.0"
sha2 = "0.9.5"
wasmparser = "0.81.0"
wasm-encoder = "0.8.0"
primitive-types = "0.10.1"
tiny-keccak = { version = "2.0", features = ["keccak"] }
serde_json = "1.0"
base64 = "0.13.0"
hex = "0.4.3"
bytes = "1.1.0"

js-sys = { version = "0.3.55", optional = true }
wasm-bindgen = { version = "0.2.78", optional = true }

[dev-dependencies]
hex-literal = "0.3.4"
criterion = { version = "0.3", features = ["async_tokio"] }
wasmer = "2.1.0"
wasmer-compiler-singlepass = "2.1.0"

[build-dependencies]
v8 = "0.34.0"
deno_core = "0.107.0"
deno_crypto = "0.39.0"
deno_url = "0.25.0"
deno_web = "0.56.0"
deno_webidl = "0.25.0"
serde = { version = "1", features = ["derive"] }

