[package]
name = "three_em"
version = "0.1.0"
authors = ["andreespirela <andreespirela@outlook.com>", "Divy Srivastava <dj.srivastava23@gmail.com>"]
edition = "2021"
resolver = "2"

[dependencies]
v8 = "0.34.0"
deno_core = "0.107.0"
tokio = { version = "1.10.1", features = ["full"] }
async-trait = "0.1.51"
