[workspace]
members = [
  "./src"
]
exclude = [
  # Rust WASM proc_macro helper.
  "./wasm_tools/rust/",
  # Node API bindings
  "./js/napi",
]
resolver = "2"

[profile.release]
lto = true

[profile.release.package.bench]
opt-level = 3
codegen-units = 1

