[workspace]
members = [
  "./crates/arweave",
  "./crates/cli",
  "./crates/evm",
  "./crates/executor",
  "./crates/js",
  "./crates/metering",
  "./crates/smartweave",
  "./crates/wasm",
]
resolver = "2"
