name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly

      - uses: Swatinem/rust-cache@v1

      - name: Run Tests
        run: cargo test

      - name: Check Formatting
        run: cargo fmt --all -- --check
